import { useState, useRef, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { useTheme } from '../App.jsx'
import aiIcon from '../assets/ai-icon.png'

const WELCOME_HOUR = new Date().getHours()
const GREETING = WELCOME_HOUR < 12 ? 'Good Morning' : WELCOME_HOUR < 17 ? 'Good Afternoon' : 'Good Evening'

function isToneRequest(text) {
  const toneKeywords = ['tone', 'settings', 'eq', 'gain', 'vst', 'plugin', 'sound like', 'recreate', 'dial in', 'preset', 'amp', 'cab', 'generate']
  const bandContext = ['metallica', 'tool', 'periphery', 'gojira', 'meshuggah', 'polyphia', 'intervals', 'architects', 'lamb of god', 'animals as leaders']
  const lower = text.toLowerCase()
  return toneKeywords.some(k => lower.includes(k)) || bandContext.some(b => lower.includes(b))
}

export default function ChatWindow({
  chat, homeState, addMessage, updateLastMessage,
  activeChatId, createChat, setActiveChatId, renameChat, navigate
}) {
  const { isDark } = useTheme()
  const [input, setInput] = useState('')
  const [isStreaming, setIsStreaming] = useState(false)
  const messagesEndRef = useRef(null)
  const inputRef = useRef(null)
  const hasAutoGenerated = useRef(false)

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [chat?.messages?.length])

  // Auto-generate when arriving from home page
  useEffect(() => {
    if (
      activeChatId &&
      homeState?.band &&
      chat?.messages?.length === 0 &&
      !hasAutoGenerated.current
    ) {
      hasAutoGenerated.current = true
      const userText = homeState.vst
        ? `Generate tone settings for ${homeState.band} using ${homeState.vst}.`
        : `Generate tone settings for ${homeState.band} (any VST).`
      streamResponse(userText, activeChatId, true)
    }
  }, [activeChatId, chat?.id])

  const streamResponse = async (userText, chatId, forceTone = false) => {
    if (!chatId) return
    setIsStreaming(true)

    const userMsg = {
      id: Date.now().toString(),
      role: 'user',
      content: userText,
    }
    addMessage(chatId, userMsg)

    const tonyMsg = {
      id: (Date.now() + 1).toString(),
      role: 'tony',
      content: '',
      streaming: true,
    }
    addMessage(chatId, tonyMsg)

    const isTone = forceTone || isToneRequest(userText)

    try {
      const res = await fetch('/api/generate-tone', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          vst_name: chat?.vst || homeState?.vst || null,
          band_name: isTone ? (chat?.band || homeState?.band || userText) : userText,
          is_general: !isTone,
          message: userText,
        }),
      })

      if (!res.ok) throw new Error(`API error ${res.status}`)

      const reader = res.body.getReader()
      const decoder = new TextDecoder()
      let fullText = ''

      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        const chunk = decoder.decode(value)
        for (const line of chunk.split('\n')) {
          if (line.startsWith('data: ')) {
            const data = line.slice(6).trim()
            if (data === '[DONE]') break
            try {
              const parsed = JSON.parse(data)
              if (parsed.token) {
                fullText += parsed.token
                updateLastMessage(chatId, fullText, true)
              }
            } catch {}
          }
        }
      }
      updateLastMessage(chatId, fullText, false)
    } catch (err) {
      updateLastMessage(chatId, `⚠️ Connection error: ${err.message}. Make sure the backend is running on port 8000.`, false)
    }
    setIsStreaming(false)
  }

  const handleSend = async () => {
    if (!input.trim() || isStreaming) return
    const msg = input.trim()
    setInput('')

    if (!activeChatId) {
      // Direct /chat access — create a new chat first
      const id = createChat(null, msg)
      if (id) {
        setActiveChatId(id)
        navigate(`/chat/${id}`, { replace: true })
        // Small delay to let state settle before streaming
        setTimeout(() => streamResponse(msg, id, isToneRequest(msg)), 150)
      }
      return
    }

    await streamResponse(msg, activeChatId, false)
  }

  // Theme
  const bg = isDark ? '#020202' : '#f0ece8'
  const headerBg = isDark ? 'rgba(8,8,8,0.6)' : 'rgba(245,240,235,0.8)'
  const headerBorder = isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.08)'
  const userMsgBg = isDark ? 'rgba(255,255,255,0.07)' : 'rgba(0,0,0,0.06)'
  const userMsgColor = isDark ? 'rgba(255,255,255,0.85)' : 'rgba(0,0,0,0.8)'
  const tonyMsgBg = isDark ? 'rgba(255,255,255,0.04)' : 'rgba(255,255,255,0.85)'
  const tonyMsgBorder = isDark ? 'rgba(255,255,255,0.07)' : 'rgba(0,0,0,0.08)'

  // Empty state — no active chat
  if (!activeChatId) {
    return (
      <div className="flex flex-col h-screen" style={{ background: bg }}>
        <div className="flex-1 flex flex-col items-center justify-center p-8">
          <motion.div
            animate={{ y: [0, -12, 0] }}
            transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}
            className="mb-8"
          >
            <div className="w-28 h-28 rounded-full overflow-hidden"
              style={{
                border: '1px solid rgba(255,255,255,0.15)',
                boxShadow: '0 0 60px rgba(3,40,184,0.25), 0 0 30px rgba(177,58,41,0.15)',
              }}>
              <img src={aiIcon} alt="Tony" className="w-full h-full object-cover" />
            </div>
          </motion.div>

          <h2 className="font-display font-bold text-2xl mb-2"
            style={{ color: isDark ? 'rgba(255,255,255,0.8)' : 'rgba(0,0,0,0.8)' }}>
            {GREETING}, Guitarist.
          </h2>
          <p className="text-sm text-center max-w-xs mb-8"
            style={{ color: isDark ? 'rgba(255,255,255,0.3)' : 'rgba(0,0,0,0.4)' }}>
            Tell me the band you want to sound like, or ask me anything.
          </p>

          <div className="w-full max-w-sm glass-strong rounded-2xl p-4">
            <div className="flex gap-2">
              <input
                ref={inputRef}
                value={input}
                onChange={e => setInput(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && handleSend()}
                placeholder="e.g. Gojira, Tool, or ask me anything..."
                className="flex-1 bg-transparent text-sm outline-none"
                style={{ color: isDark ? 'white' : '#1a1a1a' }}
              />
              <button
                onClick={handleSend}
                disabled={!input.trim()}
                className="px-4 py-2.5 rounded-xl text-sm font-medium text-white disabled:opacity-30"
                style={{ background: 'linear-gradient(135deg, #B13A29, #8a2a1c)' }}
              >
                Go
              </button>
            </div>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="flex flex-col h-screen" style={{ background: bg }}>
      {/* Header */}
      <div className="flex items-center px-6 py-4"
        style={{ background: headerBg, borderBottom: `1px solid ${headerBorder}` }}>
        <div className="flex items-center gap-2">
          <div className="w-2 h-2 rounded-full bg-[#B13A29] animate-pulse-glow" />
          <span className="text-sm font-medium"
            style={{ color: isDark ? 'rgba(255,255,255,0.6)' : 'rgba(0,0,0,0.6)' }}>
            {chat?.title || 'New Chat'}
          </span>
        </div>
        <div className="ml-auto flex items-center gap-1.5">
          <span className="text-[10px] font-mono"
            style={{ color: isDark ? 'rgba(255,255,255,0.2)' : 'rgba(0,0,0,0.25)' }}>
            TONY · RAG ACTIVE
          </span>
          <div className="w-1.5 h-1.5 rounded-full bg-green-400/60" />
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-4 py-6 space-y-4">
        <AnimatePresence initial={false}>
          {chat?.messages?.map((msg) => (
            <motion.div
              key={msg.id}
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.25 }}
              className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
            >
              {msg.role === 'tony' && (
                <div className="w-7 h-7 rounded-full overflow-hidden flex-shrink-0 mr-3 mt-1 shadow-[0_0_16px_rgba(177,58,41,0.4)]">
                  <img src={aiIcon} alt="Tony" className="w-full h-full object-cover" />
                </div>
              )}
              <div
                className={`max-w-[75%] rounded-2xl px-4 py-3 text-sm leading-relaxed ${msg.role === 'user' ? 'rounded-tr-sm' : 'rounded-tl-sm'}`}
                style={{
                  background: msg.role === 'user' ? userMsgBg : tonyMsgBg,
                  color: msg.role === 'user' ? userMsgColor : (isDark ? 'rgba(255,255,255,0.85)' : 'rgba(0,0,0,0.8)'),
                  border: msg.role === 'tony' ? `1px solid ${tonyMsgBorder}` : 'none',
                }}
              >
                {msg.role === 'tony'
                  ? <ToneContent content={msg.content} streaming={msg.streaming} isDark={isDark} />
                  : <span>{msg.content}</span>
                }
              </div>
            </motion.div>
          ))}
        </AnimatePresence>

        {/* Thinking dots */}
        {isStreaming && chat?.messages?.length > 0 &&
          !chat.messages[chat.messages.length - 1]?.content && (
          <div className="flex items-center gap-3">
            <div className="w-7 h-7 rounded-full overflow-hidden flex-shrink-0 shadow-[0_0_16px_rgba(177,58,41,0.4)]">
              <img src={aiIcon} alt="Tony" className="w-full h-full object-cover" />
            </div>
            <div className="glass rounded-2xl px-4 py-3 flex gap-1.5">
              {[0, 0.2, 0.4].map((delay, i) => (
                <div key={i} className="w-1.5 h-1.5 rounded-full bg-white/30 animate-thinking"
                  style={{ animationDelay: `${delay}s` }} />
              ))}
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="px-4 pb-5 pt-2">
        <div
          className="flex items-end gap-3 glass-strong rounded-2xl px-4 py-3"
          style={{ boxShadow: isDark ? '0 8px 32px rgba(0,0,0,0.5)' : '0 8px 32px rgba(0,0,0,0.1)' }}
        >
          <textarea
            ref={inputRef}
            value={input}
            onChange={e => setInput(e.target.value)}
            onKeyDown={e => {
              if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleSend() }
            }}
            placeholder="Ask Tony anything — tone settings, tips, gear questions..."
            rows={1}
            className="flex-1 bg-transparent text-sm resize-none outline-none leading-relaxed max-h-32"
            style={{ color: isDark ? 'white' : '#1a1a1a', scrollbarWidth: 'none' }}
          />
          <button
            onClick={handleSend}
            disabled={!input.trim() || isStreaming}
            className="w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0 transition-all duration-200 disabled:opacity-30"
            style={{
              background: input.trim() ? 'linear-gradient(135deg, #B13A29, #8a2a1c)' : (isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.06)'),
              boxShadow: input.trim() ? '0 0 20px rgba(177,58,41,0.35)' : 'none',
            }}
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
              <path d="M5 12h14M13 6l6 6-6 6" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </button>
        </div>
        <p className="text-center text-[10px] mt-2"
          style={{ color: isDark ? 'rgba(255,255,255,0.15)' : 'rgba(0,0,0,0.25)' }}>
          Tony · Guitar tone AI · Ask anything
        </p>
      </div>
    </div>
  )
}

function ToneContent({ content, streaming, isDark }) {
  if (!content) return null
  const lines = content.split('\n')

  return (
    <div className={streaming ? 'streaming-cursor' : ''}>
      {lines.map((line, i) => {
        if (/^\[.+\]$/.test(line.trim())) {
          return (
            <div key={i} className="mt-3 first:mt-0">
              <span className="text-[10px] font-bold tracking-[0.2em] uppercase px-2 py-0.5 rounded font-mono"
                style={{ color: '#B13A29', background: 'rgba(177,58,41,0.1)' }}>
                {line.trim()}
              </span>
            </div>
          )
        }
        if (
          line.includes(':') &&
          !line.startsWith('//') &&
          !line.startsWith('#') &&
          !line.startsWith('⚠') &&
          !line.toLowerCase().startsWith('note')
        ) {
          const colonIdx = line.indexOf(':')
          const key = line.slice(0, colonIdx)
          const val = line.slice(colonIdx + 1)
          return (
            <div key={i} className="flex justify-between items-baseline gap-4 py-0.5 font-mono text-[12px]">
              <span style={{ color: isDark ? 'rgba(255,255,255,0.4)' : 'rgba(0,0,0,0.45)' }}>{key}:</span>
              <span className="font-medium" style={{ color: isDark ? 'rgba(255,255,255,0.85)' : 'rgba(0,0,0,0.8)' }}>{val}</span>
            </div>
          )
        }
        if (
          line.toLowerCase().includes('low confidence') ||
          line.toLowerCase().includes('approximation') ||
          line.startsWith('⚠')
        ) {
          return (
            <div key={i} className="mt-2 text-[11px]" style={{ color: 'rgba(220,160,60,0.85)' }}>
              {line}
            </div>
          )
        }
        if (!line.trim()) return <div key={i} className="h-1" />
        return (
          <div key={i} className="text-sm leading-relaxed"
            style={{ color: isDark ? 'rgba(255,255,255,0.75)' : 'rgba(0,0,0,0.7)' }}>
            {line}
          </div>
        )
      })}
    </div>
  )
}