/**
 * ChatWindow.jsx — Main AI Chat Interface
 * -----------------------------------------
 * The primary interaction area of SonicTone AI. Handles two distinct states:
 *
 * ── EMPTY STATE (no activeChatId) ──
 *   Shows a centered card with Band input + Plugin dropdown + Generate button.
 *   Submitting creates a new chat via createChat() and fires the first tone request.
 *
 * ── ACTIVE CHAT STATE ──
 *   Shows the message list + feedback chips + text input bar.
 *   Auto-scrolls to the latest message as new tokens arrive.
 *
 * Streaming (SSE):
 *   streamResponse() POSTs to /api/generate-tone and reads the response as a
 *   Server-Sent Events stream. Each "data: {...}" line carries a { token } field
 *   which is accumulated into fullText and written to the last message via
 *   updateLastMessage(chatId, fullText, isStreaming). When the stream closes
 *   (data: [DONE]), the final content is persisted to Supabase.
 *
 *   API base URL:
 *     Production — VITE_API_URL env var (set in Vercel project settings)
 *     Local dev  — falls back to '/api' which Vite proxies to localhost:8000
 *
 * Intent detection helpers:
 *   isToneRequest(text) — detects tone-generation intent keywords
 *   isFeedback(text)    — detects tweak/adjustment keywords
 *   These determine whether the backend should run in tone-gen or general-chat mode.
 *
 * ToneContent (sub-component):
 *   Parses the AI's markdown-table-heavy response into styled React elements:
 *   markdown tables → <table>, [SECTION] headers, key: value rows, verdict badges.
 *   Adds a blinking cursor while streaming=true.
 */
import { useState, useRef, useEffect, useContext } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { useTheme, StreamingContext } from '../App.jsx'
import { VST_OPTIONS_FULL } from '../constants/vst.js'
import aiIcon from '../assets/ai-icon.png'

const WELCOME_HOUR = new Date().getHours()
const GREETING = WELCOME_HOUR < 12 ? 'Good Morning' : WELCOME_HOUR < 17 ? 'Good Afternoon' : 'Good Evening'

function isToneRequest(text) {
  const toneKeywords = ['tone', 'settings', 'eq', 'gain', 'vst', 'plugin', 'sound like',
    'recreate', 'dial in', 'preset', 'amp', 'cab', 'generate', 'brighter', 'darker', 'live tone']
  return toneKeywords.some(k => text.toLowerCase().includes(k))
}

function isFeedback(text) {
  const feedbackKeywords = ['too muddy', 'more bite', 'less gain', 'more gain', 'too bright',
    'too dark', 'tighter', 'looser', 'closer to', 'live tone', 'adjust', 'tweak', 'reduce', 'increase', 'muddy', 'bite']
  return feedbackKeywords.some(k => text.toLowerCase().includes(k))
}

export default function ChatWindow({
  chat, homeState, addMessage, updateLastMessage,
  activeChatId, createChat, setActiveChatId, renameChat, navigate, user
}) {
  const { isDark } = useTheme()
  const { setIsStreaming: setGlobalStreaming } = useContext(StreamingContext)
  const [input, setInput] = useState('')
  const [newChatBand, setNewChatBand] = useState('')
  const [newChatVst, setNewChatVst] = useState('')
  const [isStreaming, setIsStreaming] = useState(false)
  const messagesEndRef = useRef(null)
  const inputRef = useRef(null)
  const hasAutoGenerated = useRef(false)
  const chatRef = useRef(chat)
  useEffect(() => { chatRef.current = chat }, [chat])

  const setStreaming = (val) => {
    setIsStreaming(val)
    setGlobalStreaming(val)
  }

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [chat?.messages?.length])

  useEffect(() => {
    if (activeChatId && homeState?.fromHome && homeState?.band &&
      chat?.messages?.length === 0 && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true
      const userText = homeState.vst
        ? `Generate tone settings for ${homeState.band} using ${homeState.vst}.`
        : `Generate tone settings for ${homeState.band} (any VST).`
      streamResponse(userText, activeChatId, homeState.vst, homeState.band, true)
    }
  }, [activeChatId, chat?.id])

  const buildHistory = (messages) => {
    return (messages || [])
      .filter(m => (m.role === 'user' || m.role === 'sonic') && m.content)
      .map(m => ({ role: m.role === 'sonic' ? 'assistant' : 'user', content: m.content }))
  }

  const streamResponse = async (userText, chatId, vstName, bandName, forceTone = false) => {
    if (!chatId) return
    setStreaming(true)

    addMessage(chatId, { id: Date.now().toString(), role: 'user', content: userText })
    addMessage(chatId, { id: (Date.now() + 1).toString(), role: 'sonic', content: '', streaming: true })

    const isThisFeedback = isFeedback(userText)
    const isTone = forceTone || isToneRequest(userText) || isThisFeedback
    const history = buildHistory(chatRef.current?.messages || [])

    try {
      const API_BASE = import.meta.env.VITE_API_URL || '/api'
      const res = await fetch(`${API_BASE}/generate-tone`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          vst_name: vstName || null,
          band_name: bandName || userText,
          is_general: !isTone,
          message: userText,
          chat_history: history,
        }),
      })

      if (!res.ok) throw new Error(`API error ${res.status}`)

      const reader = res.body.getReader()
      const decoder = new TextDecoder()
      let fullText = ''

      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        const chunk = decoder.decode(value)
        for (const line of chunk.split('\n')) {
          if (line.startsWith('data: ')) {
            const data = line.slice(6).trim()
            if (data === '[DONE]') break
            try {
              const parsed = JSON.parse(data)
              if (parsed.token) {
                fullText += parsed.token
                updateLastMessage(chatId, fullText, true)
              }
            } catch {}
          }
        }
      }
      updateLastMessage(chatId, fullText, false)
    } catch (err) {
      updateLastMessage(chatId,
        `⚠️ Connection error: ${err.message}. Make sure the backend is running on port 8000.`, false)
    }
    setStreaming(false)
  }

  const handleSend = async () => {
    if (!input.trim() || isStreaming) return
    const msg = input.trim()
    setInput('')
    const isThisFeedback = isFeedback(msg)
    let vstName = chatRef.current?.vst || homeState?.vst || null
    let bandName = chatRef.current?.band || homeState?.band || msg
    if (!isThisFeedback && isToneRequest(msg)) { bandName = msg; vstName = null }
    await streamResponse(msg, activeChatId, vstName, bandName, false)
  }

  const handleNewChatSubmit = async () => {
    if (!newChatBand.trim()) return
    const id = await createChat(newChatVst || null, newChatBand.trim())
    if (id) {
      setActiveChatId(id)
      navigate(`/chat/${id}`, { replace: true, state: null })
      const userText = newChatVst
        ? `Generate tone settings for ${newChatBand.trim()} using ${newChatVst}.`
        : `Generate tone settings for ${newChatBand.trim()} (any VST).`
      setTimeout(() => streamResponse(userText, id, newChatVst || null, newChatBand.trim(), true), 200)
    }
  }

  const userName = user?.user_metadata?.name || 'U'
  const bg = isDark ? '#020202' : '#faf6e9'
  const headerBg = isDark ? 'rgba(4,4,2,0.8)' : 'rgba(250,246,233,0.9)'
  const userMsgBg = isDark ? 'rgba(212,175,55,0.1)' : 'rgba(212,175,55,0.12)'
  const sonicMsgBg = isDark ? 'rgba(255,255,255,0.03)' : 'rgba(255,255,255,0.85)'
  const inputColor = isDark ? '#FFD700' : '#8B6914'
  const mutedColor = isDark ? 'rgba(212,175,55,0.4)' : 'rgba(139,109,20,0.6)'
  const selectBg = isDark ? '#111' : '#faf0d0'

  // ── EMPTY STATE ──
  if (!activeChatId) {
    return (
      <div className="flex flex-col h-screen" style={{ background: bg }}>
        <div className="flex-1 flex flex-col items-center justify-center p-8">
          <motion.div animate={{ y: [0, -12, 0] }}
            transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }} className="mb-8">
            <div className="w-28 h-28 rounded-full overflow-hidden"
              style={{ border: '1px solid rgba(212,175,55,0.2)',
                boxShadow: '0 0 60px rgba(255,215,0,0.15), 0 0 30px rgba(212,175,55,0.1)' }}>
              <img src={aiIcon} alt="Sonic" className="w-full h-full object-cover" />
            </div>
          </motion.div>

          <h2 style={{ fontFamily: 'Impact, Arial, sans-serif', fontSize: '1.6rem',
            color: '#D4AF37', letterSpacing: '0.05em' }} className="mb-2">
            {GREETING.toUpperCase()}, GUITARIST.
          </h2>
          <p className="text-sm text-center max-w-xs mb-8" style={{ color: mutedColor }}>
            Select your plugin and enter a band to generate tone settings.
          </p>

          <div className="w-full max-w-sm glass-strong rounded-2xl p-5 space-y-4">
            <div>
              <label className="block text-[10px] font-semibold tracking-[0.2em] uppercase mb-2"
                style={{ color: mutedColor, fontFamily: 'Impact, Arial, sans-serif' }}>
                🎸 BAND / ARTIST
              </label>
              <input value={newChatBand} onChange={e => setNewChatBand(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && handleNewChatSubmit()}
                placeholder="e.g. Metallica, Tool, Gojira..."
                className="w-full bg-transparent text-sm outline-none rounded-xl px-3 py-2.5 transition-all"
                style={{ color: inputColor,
                  border: `1px solid ${newChatBand ? 'rgba(255,215,0,0.4)' : 'rgba(212,175,55,0.15)'}`,
                  boxShadow: newChatBand ? '0 0 12px rgba(255,215,0,0.1)' : 'none' }} />
            </div>

            <div>
              <label className="block text-[10px] font-semibold tracking-[0.2em] uppercase mb-2"
                style={{ color: mutedColor, fontFamily: 'Impact, Arial, sans-serif' }}>
                🔊 PLUGIN
              </label>
              <div className="relative">
                <select value={newChatVst} onChange={e => setNewChatVst(e.target.value)}
                  className="w-full appearance-none rounded-xl px-3 py-2.5 text-sm outline-none cursor-pointer"
                  style={{ background: 'rgba(212,175,55,0.04)', border: '1px solid rgba(212,175,55,0.15)',
                    color: inputColor }}>
                  {VST_OPTIONS_FULL.map(v => (
                    <option key={v.value} value={v.value} style={{ background: selectBg }}>{v.label}</option>
                  ))}
                </select>
                <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none">
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none">
                    <path d="M6 9l6 6 6-6" stroke={mutedColor} strokeWidth="2" strokeLinecap="round"/>
                  </svg>
                </div>
              </div>
            </div>

            <button onClick={handleNewChatSubmit} disabled={!newChatBand.trim()}
              className="w-full py-3 rounded-xl font-bold text-sm transition-all disabled:opacity-30 disabled:cursor-not-allowed"
              style={{ background: 'linear-gradient(135deg, #FFD700, #D4AF37)', color: '#020202',
                boxShadow: newChatBand.trim() ? '0 0 20px rgba(255,215,0,0.25)' : 'none',
                fontFamily: 'Impact, Arial, sans-serif', letterSpacing: '0.1em', fontSize: '0.9rem' }}>
              ⚡ GENERATE TONE
            </button>
          </div>
        </div>
      </div>
    )
  }

  // ── ACTIVE CHAT ──
  return (
    <div className="flex flex-col h-screen" style={{ background: bg }}>
      {/* Header */}
      <div className="flex items-center px-6 py-4"
        style={{ background: headerBg, borderBottom: '1px solid rgba(212,175,55,0.08)' }}>
        <div className="flex items-center gap-2">
          <div className="w-2 h-2 rounded-full animate-pulse-glow"
            style={{ background: '#FFD700', boxShadow: '0 0 8px rgba(255,215,0,0.6)' }} />
          <span className="text-sm font-medium" style={{ color: 'rgba(212,175,55,0.7)',
            fontFamily: 'Impact, Arial, sans-serif', letterSpacing: '0.05em' }}>
            {chat?.title || 'NEW CHAT'}
          </span>
        </div>
        <div className="ml-auto flex items-center gap-1.5">
          <span className="text-[10px] font-mono" style={{ color: 'rgba(212,175,55,0.2)' }}>
            SONIC · RAG ACTIVE
          </span>
          <div className="w-1.5 h-1.5 rounded-full bg-green-400/60" />
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-4 py-6 space-y-4">
        <AnimatePresence initial={false}>
          {chat?.messages
            ?.filter(msg => !(msg.role === 'sonic' && !msg.content))
            .map((msg) => (
              <motion.div key={msg.id}
                initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.25 }}
                className={`flex items-start ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>

                {/* Sonic icon — left */}
                {msg.role === 'sonic' && (
                  <div className="w-7 h-7 rounded-full overflow-hidden flex-shrink-0 mr-3 mt-1"
                    style={{ boxShadow: '0 0 12px rgba(255,215,0,0.3)' }}>
                    <img src={aiIcon} alt="Sonic" className="w-full h-full object-cover" />
                  </div>
                )}

                <div className={`max-w-[75%] rounded-2xl px-4 py-3 text-sm leading-relaxed
                  ${msg.role === 'user' ? 'rounded-tr-sm' : 'rounded-tl-sm'}`}
                  style={{
                    background: msg.role === 'user' ? userMsgBg : sonicMsgBg,
                    border: msg.role === 'user'
                      ? '1px solid rgba(212,175,55,0.2)'
                      : `1px solid ${isDark ? 'rgba(212,175,55,0.08)' : 'rgba(0,0,0,0.06)'}`,
                    color: msg.role === 'user' ? '#FFD700' : (isDark ? 'rgba(255,255,255,0.85)' : 'rgba(0,0,0,0.8)'),
                  }}>
                  {msg.role === 'sonic'
                    ? <ToneContent content={msg.content} streaming={msg.streaming} isDark={isDark} />
                    : <span>{msg.content}</span>
                  }
                </div>

                {/* User icon — right */}
                {msg.role === 'user' && (
                  <div className="w-7 h-7 rounded-full flex-shrink-0 ml-3 mt-1 flex items-center justify-center text-[11px] font-bold"
                    style={{ background: 'linear-gradient(135deg, #FFD700, #D4AF37)', color: '#020202',
                      boxShadow: '0 0 10px rgba(255,215,0,0.3)', fontFamily: 'Impact, Arial, sans-serif' }}>
                    {userName[0]?.toUpperCase()}
                  </div>
                )}
              </motion.div>
            ))}
        </AnimatePresence>

        {/* Thinking dots */}
        {isStreaming &&
          chat?.messages?.length > 0 &&
          chat.messages[chat.messages.length - 1]?.role === 'sonic' &&
          !chat.messages[chat.messages.length - 1]?.content && (
          <div className="flex items-center gap-3">
            <div className="w-7 h-7 rounded-full overflow-hidden flex-shrink-0"
              style={{ boxShadow: '0 0 12px rgba(255,215,0,0.3)' }}>
              <img src={aiIcon} alt="Sonic" className="w-full h-full object-cover" />
            </div>
            <div className="glass rounded-2xl px-4 py-3 flex gap-1.5">
              {[0, 0.2, 0.4].map((delay, i) => (
                <div key={i} className="w-1.5 h-1.5 rounded-full animate-thinking"
                  style={{ background: 'rgba(212,175,55,0.5)', animationDelay: `${delay}s` }} />
              ))}
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="px-4 pb-5 pt-2">
        <div className="flex gap-2 mb-2 flex-wrap">
          {['Too muddy', 'More bite', 'Less gain', 'Tighter low end', 'Closer to live tone'].map(chip => (
            <button key={chip} onClick={() => setInput(chip)}
              className="text-[10px] px-2.5 py-1 rounded-full transition-all"
              style={{ background: 'rgba(212,175,55,0.06)', border: '1px solid rgba(212,175,55,0.15)',
                color: 'rgba(212,175,55,0.5)' }}
              onMouseEnter={e => { e.currentTarget.style.borderColor = 'rgba(212,175,55,0.3)'; e.currentTarget.style.color = 'rgba(212,175,55,0.8)' }}
              onMouseLeave={e => { e.currentTarget.style.borderColor = 'rgba(212,175,55,0.15)'; e.currentTarget.style.color = 'rgba(212,175,55,0.5)' }}>
              {chip}
            </button>
          ))}
        </div>

        <div className="flex items-end gap-3 glass-strong rounded-2xl px-4 py-3"
          style={{ boxShadow: isDark ? '0 8px 32px rgba(0,0,0,0.5)' : '0 8px 24px rgba(0,0,0,0.08)' }}>
          <textarea ref={inputRef} value={input}
            onChange={e => setInput(e.target.value)}
            onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); handleSend() } }}
            placeholder="Ask Sonic anything, change band, tweak tone..."
            rows={1}
            className="flex-1 bg-transparent text-sm resize-none outline-none leading-relaxed max-h-32"
            style={{ color: isDark ? 'rgba(255,215,0,0.8)' : '#8B6914', scrollbarWidth: 'none' }} />
          <button onClick={handleSend} disabled={!input.trim() || isStreaming}
            className="w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0 transition-all disabled:opacity-30"
            style={{
              background: input.trim() ? 'linear-gradient(135deg, #FFD700, #D4AF37)' : 'rgba(212,175,55,0.08)',
              boxShadow: input.trim() ? '0 0 16px rgba(255,215,0,0.25)' : 'none',
            }}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
              <path d="M5 12h14M13 6l6 6-6 6" stroke={input.trim() ? '#020202' : 'rgba(212,175,55,0.4)'}
                strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </button>
        </div>

        <p className="text-center text-[10px] mt-2" style={{ color: 'rgba(212,175,55,0.15)' }}>
          Sonic · Fully conversational · Change band or plugin anytime
        </p>
      </div>
    </div>
  )
}

function ToneContent({ content, streaming, isDark }) {
  if (!content) return null

  const normalizeContent = (raw) => {
    let text = raw
    text = text.replace(/\|([^|\n]+\|)+/g, match => '\n' + match)
    text = text.replace(/(\S)\[([A-Z\s]+)\]/g, '$1\n[$2]')
    text = text.replace(/([a-z\d)])([A-Z][a-z])/g, '$1\n$2')
    return text
  }

  const lines = normalizeContent(content).split('\n')
  const result = []
  let i = 0
  let tableBuffer = []
  let inTable = false

  const flushTable = () => {
    if (tableBuffer.length < 2) {
      tableBuffer.forEach((l, idx) =>
        result.push(<div key={`tl-${i}-${idx}`} className="text-xs font-mono py-0.5"
          style={{ color: 'rgba(212,175,55,0.6)' }}>{l}</div>)
      )
      tableBuffer = []; inTable = false; return
    }

    const rows = tableBuffer
      .filter(l => l.trim() && !l.match(/^\|[-\s|]+\|$/))
      .map(l => l.split('|').filter((_, i, a) => i > 0 && i < a.length - 1).map(c => c.trim()))

    result.push(
      <div key={`table-${i}`} className="my-3 rounded-xl overflow-hidden"
        style={{ border: '1px solid rgba(212,175,55,0.15)' }}>
        <table className="w-full text-xs border-collapse">
          <tbody>
            {rows.map((row, ri) => (
              <tr key={ri} style={{
                background: ri === 0
                  ? 'rgba(212,175,55,0.12)'
                  : ri % 2 === 0
                    ? (isDark ? 'rgba(255,255,255,0.02)' : 'rgba(0,0,0,0.01)')
                    : 'transparent',
              }}>
                {row.map((cell, ci) => (
                  <td key={ci} className="px-4 py-2 font-mono"
                    style={{
                      color: ci === 0
                        ? 'rgba(212,175,55,0.6)'
                        : ri === 0
                          ? '#FFD700'
                          : (isDark ? 'rgba(255,255,255,0.85)' : 'rgba(0,0,0,0.8)'),
                      fontWeight: ri === 0 ? 600 : ci === 1 ? 500 : 400,
                      borderBottom: ri < rows.length - 1
                        ? '1px solid rgba(212,175,55,0.07)'
                        : 'none',
                      borderRight: ci < row.length - 1
                        ? '1px solid rgba(212,175,55,0.07)'
                        : 'none',
                    }}>
                    {cell}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    )
    tableBuffer = []; inTable = false
  }

  while (i < lines.length) {
    const line = lines[i]

    if (line.trim().startsWith('|')) { inTable = true; tableBuffer.push(line); i++; continue }
    if (inTable) flushTable()

    if (/^\[.+\]$/.test(line.trim())) {
      const label = line.trim()
      const isSuitability = label === '[PLUGIN SUITABILITY]'
      result.push(
        <div key={i} className="mt-4 first:mt-0 mb-2">
          <span className="text-[10px] font-bold tracking-[0.2em] uppercase px-2 py-0.5 rounded"
            style={{
              fontFamily: 'Impact, Arial, sans-serif',
              letterSpacing: '0.15em',
              color: isSuitability ? '#4ade80' : '#FFD700',
              background: isSuitability ? 'rgba(74,222,128,0.1)' : 'rgba(255,215,0,0.08)',
              border: `1px solid ${isSuitability ? 'rgba(74,222,128,0.2)' : 'rgba(255,215,0,0.15)'}`,
            }}>
            {label}
          </span>
        </div>
      )
      i++; continue
    }

    if (line.includes('Verdict:')) {
      const verdict = line.replace('Verdict:', '').trim()
      const color = verdict.includes('GOOD') ? '#4ade80' : verdict.includes('DECENT') ? '#FFD700' : '#f87171'
      result.push(
        <div key={i} className="flex items-center gap-2 my-1">
          <span className="text-[10px] font-mono" style={{ color: 'rgba(212,175,55,0.4)' }}>Verdict:</span>
          <span className="text-xs font-bold px-2 py-0.5 rounded"
            style={{ color, background: `${color}15`,
              fontFamily: 'Impact, Arial, sans-serif', letterSpacing: '0.05em' }}>
            {verdict}
          </span>
        </div>
      )
      i++; continue
    }

    if (line.includes(':') && !line.startsWith('//') && !line.startsWith('#') &&
      !line.startsWith('⚠') && !line.toLowerCase().startsWith('http')) {
      const colonIdx = line.indexOf(':')
      const key = line.slice(0, colonIdx).trim()
      const val = line.slice(colonIdx + 1).trim()
      if (key && val) {
        result.push(
          <div key={i} className="flex gap-2 py-0.5 text-xs">
            <span className="font-mono flex-shrink-0" style={{ color: 'rgba(212,175,55,0.4)' }}>{key}:</span>
            <span style={{ color: isDark ? 'rgba(255,255,255,0.8)' : 'rgba(0,0,0,0.75)' }}>{val}</span>
          </div>
        )
        i++; continue
      }
    }

    if (!line.trim()) { result.push(<div key={i} className="h-1.5" />); i++; continue }

    result.push(
      <div key={i} className="text-sm leading-relaxed"
        style={{ color: isDark ? 'rgba(255,255,255,0.7)' : 'rgba(0,0,0,0.65)' }}>
        {line}
      </div>
    )
    i++
  }

  if (inTable) flushTable()
  return <div className={streaming ? 'streaming-cursor' : ''}>{result}</div>
}