import { useState, useRef, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { useTheme } from '../App.jsx'
import aiIcon from '../assets/ai-icon.png'

const WELCOME_HOUR = new Date().getHours()
const GREETING = WELCOME_HOUR < 12 ? 'Good Morning' : WELCOME_HOUR < 17 ? 'Good Afternoon' : 'Good Evening'

const VST_OPTIONS = [
  { value: '', label: 'Any Plugin (Default)' },
  { value: 'Neural DSP Archetype Gojira', label: 'Archetype Gojira' },
  { value: 'Neural DSP Archetype Petrucci', label: 'Archetype Petrucci' },
  { value: 'Neural DSP Archetype Nolly', label: 'Archetype Nolly' },
  { value: 'Neural DSP Archetype Tim Henson', label: 'Archetype Tim Henson' },
  { value: 'Neural DSP Archetype Rabea', label: 'Archetype Rabea' },
  { value: 'Neural DSP Parallax', label: 'Neural DSP Parallax' },
  { value: 'Neural DSP Fortin Nameless', label: 'Fortin Nameless' },
  { value: 'Neural DSP Abasi Pathos', label: 'Abasi Pathos' },
  { value: 'STL Tonality Andy James', label: 'STL Andy James' },
  { value: 'STL Tonality Howard Benson', label: 'STL Howard Benson' },
]

function isToneRequest(text) {
  const toneKeywords = [
    'tone', 'settings', 'eq', 'gain', 'vst', 'plugin', 'sound like',
    'recreate', 'dial in', 'preset', 'amp', 'cab', 'generate',
    'brighter', 'darker', 'live tone',
  ]
  const lower = text.toLowerCase()
  return toneKeywords.some(k => lower.includes(k))
}

function isFeedback(text) {
  const feedbackKeywords = [
    'too muddy', 'more bite', 'less gain', 'more gain', 'too bright',
    'too dark', 'tighter', 'looser', 'closer to', 'live tone',
    'adjust', 'tweak', 'reduce', 'increase', 'muddy', 'bite',
  ]
  const lower = text.toLowerCase()
  return feedbackKeywords.some(k => lower.includes(k))
}

export default function ChatWindow({
  chat, homeState, addMessage, updateLastMessage,
  activeChatId, createChat, setActiveChatId, renameChat, navigate
}) {
  const { isDark } = useTheme()
  const [input, setInput] = useState('')
  const [newChatBand, setNewChatBand] = useState('')
  const [newChatVst, setNewChatVst] = useState('')
  const [isStreaming, setIsStreaming] = useState(false)
  const messagesEndRef = useRef(null)
  const inputRef = useRef(null)
  const hasAutoGenerated = useRef(false)

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [chat?.messages?.length])

  // Auto-generate when arriving from home
  useEffect(() => {
    if (
      activeChatId &&
      homeState?.band &&
      chat?.messages?.length === 0 &&
      !hasAutoGenerated.current
    ) {
      hasAutoGenerated.current = true
      const userText = homeState.vst
        ? `Generate tone settings for ${homeState.band} using ${homeState.vst}.`
        : `Generate tone settings for ${homeState.band} (any VST).`
      streamResponse(userText, activeChatId, true)
    }
  }, [activeChatId, chat?.id])

  const buildHistory = (messages) => {
    return (messages || [])
      .filter(m => (m.role === 'user' || m.role === 'tony') && m.content)
      .map(m => ({
        role: m.role === 'tony' ? 'assistant' : 'user',
        content: m.content,
      }))
  }

  const streamResponse = async (userText, chatId, forceTone = false) => {
    if (!chatId) return
    setIsStreaming(true)

    const userMsg = {
      id: Date.now().toString(),
      role: 'user',
      content: userText,
    }
    addMessage(chatId, userMsg)

    const tonyMsg = {
      id: (Date.now() + 1).toString(),
      role: 'tony',
      content: '',
      streaming: true,
    }
    addMessage(chatId, tonyMsg)

    const isThisFeedback = isFeedback(userText)
    const isTone = forceTone || isToneRequest(userText) || isThisFeedback
    const currentMessages = chat?.messages || []
    const history = buildHistory(currentMessages)

    // Always preserve plugin and band from chat context
    let bandName = chat?.band || homeState?.band || userText
    let vstName = chat?.vst || homeState?.vst || null

    // Only reset context for a completely new band/plugin request
    // Never reset on feedback — keep existing plugin + band
    if (!forceTone && isTone && !isThisFeedback) {
      bandName = userText
      vstName = null
    }

    try {
      const res = await fetch('/api/generate-tone', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          vst_name: vstName,
          band_name: bandName,
          is_general: !isTone,
          message: userText,
          chat_history: history,
        }),
      })

      if (!res.ok) throw new Error(`API error ${res.status}`)

      const reader = res.body.getReader()
      const decoder = new TextDecoder()
      let fullText = ''

      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        const chunk = decoder.decode(value)
        for (const line of chunk.split('\n')) {
          if (line.startsWith('data: ')) {
            const data = line.slice(6).trim()
            if (data === '[DONE]') break
            try {
              const parsed = JSON.parse(data)
              if (parsed.token) {
                fullText += parsed.token
                updateLastMessage(chatId, fullText, true)
              }
            } catch {}
          }
        }
      }
      updateLastMessage(chatId, fullText, false)
    } catch (err) {
      updateLastMessage(
        chatId,
        `⚠️ Connection error: ${err.message}. Make sure the backend is running on port 8000.`,
        false
      )
    }
    setIsStreaming(false)
  }

  const handleSend = async () => {
    if (!input.trim() || isStreaming) return
    const msg = input.trim()
    setInput('')
    await streamResponse(msg, activeChatId, false)
  }

  const handleNewChatSubmit = () => {
    if (!newChatBand.trim()) return
    const id = createChat(newChatVst || null, newChatBand.trim())
    if (id) {
      setActiveChatId(id)
      navigate(`/chat/${id}`, { replace: true })
      const userText = newChatVst
        ? `Generate tone settings for ${newChatBand.trim()} using ${newChatVst}.`
        : `Generate tone settings for ${newChatBand.trim()} (any VST).`
      setTimeout(() => streamResponse(userText, id, true), 150)
    }
  }

  // Theme values
  const bg = isDark ? '#020202' : '#f0ece8'
  const headerBg = isDark ? 'rgba(8,8,8,0.6)' : 'rgba(245,240,235,0.8)'
  const headerBorder = isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.08)'
  const userMsgBg = isDark ? 'rgba(255,255,255,0.07)' : 'rgba(0,0,0,0.06)'
  const userMsgColor = isDark ? 'rgba(255,255,255,0.85)' : 'rgba(0,0,0,0.8)'
  const tonyMsgBg = isDark ? 'rgba(255,255,255,0.04)' : 'rgba(255,255,255,0.9)'
  const tonyMsgBorder = isDark ? 'rgba(255,255,255,0.07)' : 'rgba(0,0,0,0.08)'
  const inputColor = isDark ? 'white' : '#1a1a1a'
  const mutedColor = isDark ? 'rgba(255,255,255,0.3)' : 'rgba(0,0,0,0.4)'
  const selectBg = isDark ? '#111' : '#f8f5f2'

  // ── EMPTY STATE — new chat form ──
  if (!activeChatId) {
    return (
      <div className="flex flex-col h-screen" style={{ background: bg }}>
        <div className="flex-1 flex flex-col items-center justify-center p-8">

          <motion.div
            animate={{ y: [0, -12, 0] }}
            transition={{ duration: 4, repeat: Infinity, ease: 'easeInOut' }}
            className="mb-8"
          >
            <div className="w-28 h-28 rounded-full overflow-hidden"
              style={{
                border: '1px solid rgba(255,255,255,0.15)',
                boxShadow: '0 0 60px rgba(3,40,184,0.25), 0 0 30px rgba(177,58,41,0.15)',
              }}>
              <img src={aiIcon} alt="Tony" className="w-full h-full object-cover" />
            </div>
          </motion.div>

          <h2 className="font-display font-bold text-2xl mb-2"
            style={{ color: isDark ? 'rgba(255,255,255,0.8)' : 'rgba(0,0,0,0.8)' }}>
            {GREETING}, Guitarist.
          </h2>
          <p className="text-sm text-center max-w-xs mb-8" style={{ color: mutedColor }}>
            Select your plugin and enter a band to generate tone settings.
          </p>

          <div className="w-full max-w-sm glass-strong rounded-2xl p-5 space-y-4">

            {/* Band input */}
            <div>
              <label className="block text-[10px] font-semibold tracking-[0.15em] uppercase mb-2"
                style={{ color: mutedColor }}>
                🎸 Band / Artist
              </label>
              <input
                value={newChatBand}
                onChange={e => setNewChatBand(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && handleNewChatSubmit()}
                placeholder="e.g. Metallica, Tool, Gojira..."
                className="w-full bg-transparent text-sm outline-none border rounded-xl px-3 py-2.5 transition-all"
                style={{
                  color: inputColor,
                  borderColor: newChatBand
                    ? 'rgba(177,58,41,0.6)'
                    : (isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.12)'),
                  boxShadow: newChatBand ? '0 0 12px rgba(177,58,41,0.2)' : 'none',
                }}
              />
            </div>

            {/* Plugin dropdown */}
            <div>
              <label className="block text-[10px] font-semibold tracking-[0.15em] uppercase mb-2"
                style={{ color: mutedColor }}>
                🔊 Plugin
              </label>
              <div className="relative">
                <select
                  value={newChatVst}
                  onChange={e => setNewChatVst(e.target.value)}
                  className="w-full appearance-none border rounded-xl px-3 py-2.5 text-sm outline-none cursor-pointer"
                  style={{
                    background: isDark ? 'rgba(255,255,255,0.04)' : 'rgba(0,0,0,0.04)',
                    borderColor: isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.12)',
                    color: inputColor,
                  }}
                >
                  {VST_OPTIONS.map(v => (
                    <option key={v.value} value={v.value} style={{ background: selectBg }}>
                      {v.label}
                    </option>
                  ))}
                </select>
                <div className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none">
                  <svg width="12" height="12" viewBox="0 0 24 24" fill="none">
                    <path d="M6 9l6 6 6-6" stroke={mutedColor} strokeWidth="2" strokeLinecap="round"/>
                  </svg>
                </div>
              </div>
            </div>

            {/* Submit */}
            <button
              onClick={handleNewChatSubmit}
              disabled={!newChatBand.trim()}
              className="w-full py-3 rounded-xl text-sm font-semibold text-white transition-all disabled:opacity-30 disabled:cursor-not-allowed"
              style={{
                background: 'linear-gradient(135deg, #B13A29, #8a2a1c)',
                boxShadow: newChatBand.trim() ? '0 0 20px rgba(177,58,41,0.4)' : 'none',
              }}
            >
              ⚡ Generate Tone
            </button>
          </div>
        </div>
      </div>
    )
  }

  // ── ACTIVE CHAT ──
  return (
    <div className="flex flex-col h-screen" style={{ background: bg }}>

      {/* Header */}
      <div className="flex items-center px-6 py-4"
        style={{ background: headerBg, borderBottom: `1px solid ${headerBorder}` }}>
        <div className="flex items-center gap-2">
          <div className="w-2 h-2 rounded-full bg-[#B13A29] animate-pulse-glow" />
          <span className="text-sm font-medium"
            style={{ color: isDark ? 'rgba(255,255,255,0.6)' : 'rgba(0,0,0,0.6)' }}>
            {chat?.title || 'New Chat'}
          </span>
        </div>
        <div className="ml-auto flex items-center gap-1.5">
          <span className="text-[10px] font-mono"
            style={{ color: isDark ? 'rgba(255,255,255,0.2)' : 'rgba(0,0,0,0.25)' }}>
            TONY · RAG ACTIVE
          </span>
          <div className="w-1.5 h-1.5 rounded-full bg-green-400/60" />
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-4 py-6 space-y-4">
        <AnimatePresence initial={false}>
          {chat?.messages
            ?.filter(msg => !(msg.role === 'tony' && !msg.content))
            .map((msg) => (
              <motion.div
                key={msg.id}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.25 }}
                className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}
              >
                {msg.role === 'tony' && (
                  <div className="w-7 h-7 rounded-full overflow-hidden flex-shrink-0 mr-3 mt-1 shadow-[0_0_16px_rgba(177,58,41,0.4)]">
                    <img src={aiIcon} alt="Tony" className="w-full h-full object-cover" />
                  </div>
                )}
                <div
                  className={`max-w-[78%] rounded-2xl px-4 py-3 text-sm leading-relaxed ${msg.role === 'user' ? 'rounded-tr-sm' : 'rounded-tl-sm'}`}
                  style={{
                    background: msg.role === 'user' ? userMsgBg : tonyMsgBg,
                    color: msg.role === 'user'
                      ? userMsgColor
                      : (isDark ? 'rgba(255,255,255,0.85)' : 'rgba(0,0,0,0.8)'),
                    border: msg.role === 'tony' ? `1px solid ${tonyMsgBorder}` : 'none',
                  }}
                >
                  {msg.role === 'tony'
                    ? <ToneContent content={msg.content} streaming={msg.streaming} isDark={isDark} />
                    : <span>{msg.content}</span>
                  }
                </div>
              </motion.div>
            ))}
        </AnimatePresence>

        {/* Thinking dots */}
        {isStreaming &&
          chat?.messages?.length > 0 &&
          chat.messages[chat.messages.length - 1]?.role === 'tony' &&
          !chat.messages[chat.messages.length - 1]?.content && (
          <div className="flex items-center gap-3">
            <div className="w-7 h-7 rounded-full overflow-hidden flex-shrink-0 shadow-[0_0_16px_rgba(177,58,41,0.4)]">
              <img src={aiIcon} alt="Tony" className="w-full h-full object-cover" />
            </div>
            <div className="glass rounded-2xl px-4 py-3 flex gap-1.5">
              {[0, 0.2, 0.4].map((delay, i) => (
                <div key={i} className="w-1.5 h-1.5 rounded-full bg-white/30 animate-thinking"
                  style={{ animationDelay: `${delay}s` }} />
              ))}
            </div>
          </div>
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Input area */}
      <div className="px-4 pb-5 pt-2">

        {/* Quick feedback chips */}
        <div className="flex gap-2 mb-2 flex-wrap">
          {['Too muddy', 'More bite', 'Less gain', 'Tighter low end', 'Closer to live tone'].map(chip => (
            <button
              key={chip}
              onClick={() => setInput(chip)}
              className="text-[10px] px-2.5 py-1 rounded-full transition-all"
              style={{
                background: isDark ? 'rgba(255,255,255,0.05)' : 'rgba(0,0,0,0.05)',
                border: isDark ? '1px solid rgba(255,255,255,0.08)' : '1px solid rgba(0,0,0,0.08)',
                color: isDark ? 'rgba(255,255,255,0.4)' : 'rgba(0,0,0,0.4)',
              }}
            >
              {chip}
            </button>
          ))}
        </div>

        <div
          className="flex items-end gap-3 glass-strong rounded-2xl px-4 py-3"
          style={{
            boxShadow: isDark ? '0 8px 32px rgba(0,0,0,0.5)' : '0 8px 32px rgba(0,0,0,0.1)',
          }}
        >
          <textarea
            ref={inputRef}
            value={input}
            onChange={e => setInput(e.target.value)}
            onKeyDown={e => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault()
                handleSend()
              }
            }}
            placeholder="Ask Tony anything, change band, tweak tone..."
            rows={1}
            className="flex-1 bg-transparent text-sm resize-none outline-none leading-relaxed max-h-32"
            style={{ color: inputColor, scrollbarWidth: 'none' }}
          />
          <button
            onClick={handleSend}
            disabled={!input.trim() || isStreaming}
            className="w-9 h-9 rounded-xl flex items-center justify-center flex-shrink-0 transition-all duration-200 disabled:opacity-30"
            style={{
              background: input.trim()
                ? 'linear-gradient(135deg, #B13A29, #8a2a1c)'
                : (isDark ? 'rgba(255,255,255,0.06)' : 'rgba(0,0,0,0.06)'),
              boxShadow: input.trim() ? '0 0 20px rgba(177,58,41,0.35)' : 'none',
            }}
          >
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none">
              <path d="M5 12h14M13 6l6 6-6 6" stroke="white" strokeWidth="2"
                strokeLinecap="round" strokeLinejoin="round"/>
            </svg>
          </button>
        </div>

        <p className="text-center text-[10px] mt-2"
          style={{ color: isDark ? 'rgba(255,255,255,0.15)' : 'rgba(0,0,0,0.25)' }}>
          Tony · Fully conversational · Change band or plugin anytime
        </p>
      </div>
    </div>
  )
}

// ── Renders Tony's response ──
function ToneContent({ content, streaming, isDark }) {
  if (!content) return null

  const normalizeContent = (raw) => {
    let text = raw
    // Fix tables squished onto one line
    text = text.replace(/\|([^|\n]+\|)+/g, match => '\n' + match)
    // Fix section headers merged with previous text
    text = text.replace(/(\S)\[([A-Z\s]+)\]/g, '$1\n[$2]')
    // Fix key:value lines merged together
    text = text.replace(/([a-z\d)])([A-Z][a-z])/g, '$1\n$2')
    return text
  }

  const processedContent = normalizeContent(content)
  const lines = processedContent.split('\n')
  const result = []
  let i = 0
  let tableBuffer = []
  let inTable = false

  const flushTable = () => {
    if (tableBuffer.length < 2) {
      tableBuffer.forEach((l, idx) =>
        result.push(
          <div key={`tl-${i}-${idx}`} className="text-xs font-mono py-0.5"
            style={{ color: isDark ? 'rgba(255,255,255,0.7)' : 'rgba(0,0,0,0.7)' }}>
            {l}
          </div>
        )
      )
      tableBuffer = []
      inTable = false
      return
    }

    const rows = tableBuffer
      .filter(l => l.trim() && !l.match(/^\|[-\s|]+\|$/))
      .map(l =>
        l.split('|')
          .filter((_, idx, a) => idx > 0 && idx < a.length - 1)
          .map(c => c.trim())
      )

    result.push(
      <div key={`table-${i}`} className="my-2 rounded-xl overflow-hidden"
        style={{
          border: isDark ? '1px solid rgba(255,255,255,0.08)' : '1px solid rgba(0,0,0,0.08)',
        }}>
        <table className="w-full text-xs">
          <tbody>
            {rows.map((row, ri) => (
              <tr key={ri} style={{
                background: ri === 0
                  ? (isDark ? 'rgba(177,58,41,0.15)' : 'rgba(177,58,41,0.08)')
                  : ri % 2 === 0
                    ? (isDark ? 'rgba(255,255,255,0.03)' : 'rgba(0,0,0,0.02)')
                    : 'transparent',
              }}>
                {row.map((cell, ci) => (
                  <td key={ci} className="px-3 py-1.5 font-mono"
                    style={{
                      color: ci === 0
                        ? (isDark ? 'rgba(255,255,255,0.5)' : 'rgba(0,0,0,0.5)')
                        : (isDark ? 'rgba(255,255,255,0.9)' : 'rgba(0,0,0,0.85)'),
                      fontWeight: ci === 1 ? 500 : 400,
                      borderBottom: ri < rows.length - 1
                        ? (isDark ? '1px solid rgba(255,255,255,0.05)' : '1px solid rgba(0,0,0,0.05)')
                        : 'none',
                    }}>
                    {cell}
                  </td>
                ))}
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    )
    tableBuffer = []
    inTable = false
  }

  while (i < lines.length) {
    const line = lines[i]

    if (line.trim().startsWith('|')) {
      inTable = true
      tableBuffer.push(line)
      i++
      continue
    }

    if (inTable) flushTable()

    // Section headers [AMP], [CAB], [PLUGIN SUITABILITY] etc.
    if (/^\[.+\]$/.test(line.trim())) {
      const label = line.trim()
      const isGood = label === '[PLUGIN SUITABILITY]'
      result.push(
        <div key={i} className="mt-4 first:mt-0 mb-1">
          <span className="text-[10px] font-bold tracking-[0.18em] uppercase px-2 py-0.5 rounded font-mono"
            style={{
              color: isGood ? '#4ade80' : '#B13A29',
              background: isGood ? 'rgba(74,222,128,0.1)' : 'rgba(177,58,41,0.1)',
            }}>
            {label}
          </span>
        </div>
      )
      i++
      continue
    }

    // Verdict line
    if (line.includes('Verdict:')) {
      const verdict = line.replace('Verdict:', '').trim()
      const color = verdict.includes('GOOD')
        ? '#4ade80'
        : verdict.includes('DECENT') ? '#facc15' : '#f87171'
      result.push(
        <div key={i} className="flex items-center gap-2 my-1">
          <span className="text-[10px] font-mono"
            style={{ color: isDark ? 'rgba(255,255,255,0.4)' : 'rgba(0,0,0,0.4)' }}>
            Verdict:
          </span>
          <span className="text-xs font-bold px-2 py-0.5 rounded"
            style={{ color, background: `${color}18` }}>
            {verdict}
          </span>
        </div>
      )
      i++
      continue
    }

    // Key: Value lines
    if (
      line.includes(':') &&
      !line.startsWith('//') &&
      !line.startsWith('#') &&
      !line.startsWith('⚠') &&
      !line.toLowerCase().startsWith('http')
    ) {
      const colonIdx = line.indexOf(':')
      const key = line.slice(0, colonIdx).trim()
      const val = line.slice(colonIdx + 1).trim()
      if (key && val) {
        result.push(
          <div key={i} className="flex gap-2 py-0.5 text-xs">
            <span className="font-mono flex-shrink-0"
              style={{ color: isDark ? 'rgba(255,255,255,0.4)' : 'rgba(0,0,0,0.4)' }}>
              {key}:
            </span>
            <span style={{ color: isDark ? 'rgba(255,255,255,0.8)' : 'rgba(0,0,0,0.75)' }}>
              {val}
            </span>
          </div>
        )
        i++
        continue
      }
    }

    // Empty line
    if (!line.trim()) {
      result.push(<div key={i} className="h-1.5" />)
      i++
      continue
    }

    // Plain text
    result.push(
      <div key={i} className="text-sm leading-relaxed"
        style={{ color: isDark ? 'rgba(255,255,255,0.75)' : 'rgba(0,0,0,0.7)' }}>
        {line}
      </div>
    )
    i++
  }

  if (inTable) flushTable()

  return (
    <div className={streaming ? 'streaming-cursor' : ''}>
      {result}
    </div>
  )
}